{{- if .Values.pachd.externalService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations: {{ toYaml .Values.pachd.externalService.annotations | nindent 4 }}
  labels:
    app: pachd
    suite: pachyderm
  name: pachd-lb
  namespace: {{ .Release.Namespace }}
spec:
  ports: 
  {{- if .Values.pachd.externalService.serviceProxy }}
  - name: http
    port: 80
  {{- if .Values.pachd.tls.enabled }}
  - name: https
    port: 443
  {{- end }}
  selector:
    app: pachd-proxy
  {{ else -}}
  - name: api-grpc-port
    port: {{ .Values.pachd.externalService.apiGRPCPort }}
    targetPort: api-grpc-port
  - name: s3gateway-port
    port: {{ .Values.pachd.externalService.s3GatewayPort }} 
    targetPort: s3gateway-port
  selector:
    app: pachd
  {{ end -}}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.pachd.externalService.loadBalancerIP }}
{{ end -}}
