kind: Deployment
metadata:
annotations:
labels:
    app: pachyderm-envoy
name: pachyderm-envoy
namespace: {{ .Release.Namespace }}
spec:
replicas: 1
selector:
    matchLabels:
    app: pachyderm-envoy
template:
    metadata:
    labels:
        app: pachyderm-envoy
    spec:
    containers:
    - args:
        - -c
        - /etc/envoy/envoy.yaml
        - --service-node
        - $(MY_POD_NAME)
        - --service-zone
        - $(MY_NODE_NAME)
        - --service-cluster
        - pachyderm-envoy
        command:
        - envoy
        env:
        - name: MY_NODE_NAME
        valueFrom:
            fieldRef:
            fieldPath: spec.nodeName
        - name: MY_POD_NAME
        valueFrom:
            fieldRef:
            fieldPath: metadata.name
        image: envoyproxy/envoy:v1.20.1
        livenessProbe:
        httpGet:
            path: /server_info
            port: 9901
        name: envoy
        ports:
        - containerPort: 9901
        name: envoy-admin
        - containerPort: 80
        name: http
        - containerPort: 443
        name: https
        readinessProbe:
        httpGet:
            path: /ready
            port: 9901
        resources:
        limits:
            memory: 2048Mi
        requests:
            cpu: 1
            memory: 2048Mi
        volumeMounts:
        - mountPath: /etc/envoy
        name: envoy-config
    volumes:
    - configMap:
        name: envoy-config
      {{- if .Values.pachd.tls.enabled }}
    - name: pachd-tls-cert
      secret:
        secretName: {{ required "If external-service.tls.enabled, you must set external-service.tls.secretName" .Values.external-service.tls.secretName | quote }}
      {{- end }}
