kind: Service
metadata:
  labels:
    app: pachyderm-envoy
  name: pachyderm-envoy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: pachyderm-envoy
  type: LoadBalancer
