{{- if .Values.pachd.externalService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations: {{ toYaml .Values.pachd.externalService.annotations | nindent 4 }}
  labels:
    app: pachd
    suite: pachyderm
  name: pachd-lb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
{{- if .Values.pachd.externalService.tls.enabled }}
  - name: https
    port: 443
{{- end }}
  selector:
    app: pachyderm-envoy
  type: LoadBalancer
  loadBalancerIP: {{ .Values.pachd.externalService.loadBalancerIP }}
{{ end -}}
